server:
  port: 8081
spring:
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: mykeyspace
      entity-base-package: com.example.cassandra.springbootcassandrademo.model
